### ISSUE TITLE
Cannot destructure property 'origin' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by LIUSHUAI2018** [halo951/axios-plugins#1]
使用时报这个错误
![image](https://github.com/halo951/axios-plugins/assets/37928107/e6c2734b-c15a-492b-a37b-756bd487eaa3)

**Comment by halo951** [comment]
是哪个插件报的 麻烦提供下信息

**Comment by LIUSHUAI2018** [comment]
![image](https://github.com/halo951/axios-plugins/assets/37928107/fab5de51-43dd-4c45-b181-90b42fcd474b)
这个插件报的

**Comment by LIUSHUAI2018** [comment]
![image](https://github.com/halo951/axios-plugins/assets/37928107/5ef71b5a-b121-4c42-8048-4867e85b7eec)
woka我看定位是在这里
