### ISSUE TITLE
不支持按需引入

### ISSUE THREAD

**Issue by tangyuhui** [halo951/axios-plugins#2]
<img width="746" alt="image" src="https://github.com/halo951/axios-plugins/assets/12007803/73c11676-3f64-4465-83c9-766c512a1b77">

这是因为我不是 ts项目吗？

**Comment by tangyuhui** [comment]
<img width="705" alt="image" src="https://github.com/halo951/axios-plugins/assets/12007803/0beeda83-26a3-4390-908d-50ac1427b29f">

**Comment by halo951** [comment]
因为后面搞unbuild给按需引用搞废了... 我之前也在头疼这个. 年前没看这个项目~ 最近瞅瞅重新捡起来吧.
