### ISSUE TITLE
合并请求把错误的请求也合并了

### ISSUE THREAD

**Issue by RanMaoting** [halo951/axios-plugins#3]
合并请求把错误的请求也合并了,
![Snipaste_2024-03-06_16-13-26](https://github.com/halo951/axios-plugins/assets/62940878/1a46c961-bd2f-49e1-ba50-8d3ad230d37a)
当前一个请求权限验证失败时会刷新权限,正常应该再发起一次前面的请求,但是他被合并了,导致异常,这种如何处理

**Comment by halo951** [comment]
sorry, 之前没看这个项目. 这个你价格 exclude 排除下权限接口是否可行呢?
