### ISSUE TITLE
请教一下为什么我配置了但是没有效果

### ISSUE THREAD

**Issue by Sharang-heng** [halo951/axios-plugins#5]
我是这样配置的
![image](https://github.com/halo951/axios-plugins/assets/69613396/014893b0-4bd0-442e-9180-d015356e06c5)
但是似乎还是发起了请求
![image](https://github.com/halo951/axios-plugins/assets/69613396/5c993c7f-4188-4ea1-8476-f747cf934ca7)

 "axios-plugins": "^0.4.1",

**Comment by halo951** [comment]
这样, 然后就是检查你的 include 规则看对不. 遵循 vite 那套
```
useAxiosPlugin(instance)
 .plugin(merge({ include: '/admin/' }))
```
