### ISSUE TITLE
节流不起效果了

### ISSUE THREAD

**Issue by LuckyYunPeng** [halo951/axios-plugins#7]
节流不起效果了

**Comment by halo951** [comment]
是不是参数有差异. 或者在插件参数里面, 传入一个 calcRequestHash 方法 自行实现一下请求diff试试呢

**Comment by LuckyYunPeng** [comment]
先不试了，换了个别的写法

**Comment by halo951** [comment]
可以的. 我记得当时我这设计的通过 url+data+params 组合以后算出一个hash值, 你看看要不生效的话, 问题可能就出在这块了.
